Початок роботи з бібліотекою Numpy

У даній лабораторній роботі розглянуто наступний функціонал бібліотеки Numpy:

Створення масиву.

Відображення масивів .

Базові операції з масивами.

Завдання 1

Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [3]:
size = 11
arr = np.zeros((size,size))

In [ ]:
print(arr)

In [ ]:
for i in range(size):
  arr[i][i] = 1
  arr[i][(i-10)*-1] = 1

In [ ]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Завдання 2

Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки.

In [40]:

size = 255

Горизонтальнi градієнти

In [42]:
horizontal_gradient1 = np.zeros((size,size))
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]
for i in range(size):
    for j in range(size):
        horizontal_gradient1[i][j] = j
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

In [44]:
horizontal_gradient2 = np.zeros((size,size))
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]
for i in range(size):
    for j in range(size):
        horizontal_gradient2[i][j] = 255-j
cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)

True


Вертикальні градієнти

In [47]:
vertical_gradient1 = np.zeros((size,size))
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]
for i in range(size):
    for j in range(size):
        vertical_gradient1[i][j] = i
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

In [48]:
vertical_gradient2 = np.zeros((size,size))
w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]
for i in range(size):
    for j in range(size):
        vertical_gradient2[i][j] = 255-i
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)

True